[package]
name = "decrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
aes = "0.8.4"
rsa = "0.9.7"
openssl = "0.10.71"
pkcs1 = "0.7.5"
pem = "3.0.4"
chrono = "0.4"
clap = { version = "4.5.35", features = ["derive"] }